### ISSUE TITLE
InfoPanel animation not working

### ISSUE THREAD

**Issue by HommerDK** [MikeSiLVO/skin.aeon.nox.silvo#211]
The animation of the InfoPanel (slide in, fade in) in some library views (e.g. Showcase, Logo, Shift) is not working.
The animation works, when using "manual" mode, but when set to automatic with delay, the infopanel pops in instantly without animation.

_Manual mode turned off:_
![infopanel](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/139130017/1c7c213c-888a-4f28-8720-d001c1cfb027)

_Delay on InfoPanel turned on:_
![delay_infopanel](https://github.com/MikeSiLVO/skin.aeon.nox.silvo/assets/139130017/c6c5ee7e-2b5a-422e-a464-04c19bca95c0)

**Comment by MikeSiLVO** [comment]
Try latest version please.

9ce202a should fix it

**Comment by HommerDK** [comment]
Thanks for your quick reply.
I just tried a clean Kodi install and downloaded the 9.1.4 version of Aeon Nox Silvo, but the issue still persist. There is no InfoPanel fade in/slide in animation when flipping through the library.

**Comment by MikeSiLVO** [comment]
GitHub version

**Comment by HommerDK** [comment]
Ah, sorry. I upgraded to Kodi Omega and your fix works perfectly now.
Thank you very much.

An upgrade to your fix maybe:
When changing movie as the InfoPanel slides out, it has the new movies info on it. If possible it should keep the info from the previous movie, and first change when the new infopanel slides in.

**Comment by MikeSiLVO** [comment]
I can only hide the info. The scroll delay is just visual, the item is already selected before the animation completes.
